# Generated by Django 2.2.7 on 2020-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('regAge', models.IntegerField()),
                ('regSex', models.IntegerField()),
                ('regEmail', models.EmailField(max_length=255)),
                ('regPhoto', models.ImageField(upload_to='avatar')),
                ('regTime', models.DateTimeField(auto_now=True)),
                ('loginTime', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
