# Generated by Django 2.2.7 on 2020-02-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Voice'),
        ),
    ]
