# Generated by Django 2.2.7 on 2020-02-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postPageviews',
            field=models.IntegerField(default=0),
        ),
    ]
