# Generated by Django 2.2.7 on 2020-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20200224_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regPhoto',
            field=models.ImageField(default='/static/headPhoto/default/default.jpg', upload_to='headphoto'),
        ),
    ]
