# Generated by Django 2.2.7 on 2020-02-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20200227_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
